---

- validate:
    schema:
      type: object
      properties:
        device:
          type: string
        filesystem:
          type: string
          enum:
            - ext4
          default: ext4
      required:
        - device
        - filesystem
    instance: "{{ common }}"
  register: common_validated

- set_fact:
    common_v: "{{ common_validated.result }}"

- name: "Format {{ common_v.device }} using {{ common_v.filesystem }}"
  filesystem:
    fstype: ext4
    dev: "{{ common_v.device }}"
    opts: -m 0 -F -E lazy_itable_init=0,lazy_journal_init=0,discard
  become: yes
  when: common_v.filesystem == 'ext4'