---

- block:
    - validate:
        schema:
          type: object
          properties:
            command:
              type: string
              enum:
                - controller_reset_connection
                - reboot
                - reboot_if_requested
        instance: "{{ common }}"

    - include_tasks: '{{ common.command }}.yml'
  when: not dependency
