---

- validate:
    schema:
      type: object
      properties:
        command:
          type: string
          enum:
            - controller_reset_connection
            - dependency
            - format_device
            - reboot
            - reboot_if_requested
            - update_packages
            - upgrade_packages
      required:
        - command
    instance: "{{ common }}"

- include_tasks: '{{ common.command }}.yml'
  when: common.command != 'dependency'
