---

- block:
    - validate:
        schema:
          type: object
          properties:
            command:
              type: string
              enum:
                - controller_reset_connection
        instance: "{{ common }}"

    - include_tasks: '{{ common.command }}.yml'
  when: common is defined
