---

- name: "Flush handlers to see if reboot is requested"
  meta: flush_handlers

- block
    - import_tasks: ./reboot.yml

    - name: "Reset the reboot flag"
      set_fact:
        common_reboot_requested: no
  when: common_reboot_requested
