---

- block:
    - validate:
        schema:
          type: object
          properties:
            autoclean:
              type: boolean
              default: yes
            autoremove:
              type: boolean
              default: yes
            force_apt_get:
              type: boolean
              default: true
            type:
              type: string
              enum:
                - full
                - safe
              default: safe
            update_cache:
              type: boolean
              default: false
          required:
            - autoclean
            - autoremove
            - force_apt_get
            - type
            - update_cache
        instance: "{{ common }}"
      register: common_validated

    - set_fact:
        common_v: "{{ common_validated.result }}"

    - name: "Upgrade Apt packages"
      apt:
        autoclean: "{{ common_v.autoclean }}"
        autoremove: "{{ common_v.autoremove }}"
        force_apt_get: "{{ common_v.force_apt_get }}"
        update_cache: "{{ common_v.update_cache }}"
        upgrade: "{{ common_v.type }}"
      become: yes
  tags:
    - common_upgrade_packages
